name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build backend
      run: docker build kart-dashboard-backend --file kart-dashboard-backend/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build frontend
      run: docker build kart-dashboard-client --file kart-dashboard-client/Dockerfile --tag my-image-name:$(date +%s)

